/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import dao.ProdutoDao;
import java.sql.SQLException;
import java.util.List;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.ProdutoModelo;

/**
 *
 * @author João Pedro
 */
public class Produto extends javax.swing.JInternalFrame {

    ProdutoDao produtoDao = new ProdutoDao();
    private List<ProdutoModelo> produtos;
    private ProdutoModelo produtoSelecionado;

    /**
     * Creates new form Produtos
     */
    public Produto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_cadastrar = new javax.swing.JButton();
        btn_buscar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_alterar = new javax.swing.JButton();
        tf_descricao = new javax.swing.JTextField();
        btn_salvar = new javax.swing.JButton();
        tf_quantidade = new javax.swing.JTextField();
        btn_cancelar = new javax.swing.JButton();
        tf_custo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_venda = new javax.swing.JTextField();
        tf_codigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_buscar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabela_produto = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        tf_departamento = new javax.swing.JTextField();
        tf_marca = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Marca = new javax.swing.JLabel();

        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel1.setText("Produtos");

        btn_alterar.setText("Alterar");
        btn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterarActionPerformed(evt);
            }
        });

        btn_salvar.setText("Salvar");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        jLabel6.setText("Codigo");

        jLabel2.setText("Descrição");

        jLabel3.setText("Quantidade");

        jLabel4.setText("Valor Custo");

        tabela_produto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Descrição", "Quantidade", "Valor Custo", "Valor Venda", "Departamento", "Marca"
            }
        ));
        jScrollPane3.setViewportView(tabela_produto);

        jLabel5.setText("Valor Venda");

        jLabel7.setText("Departamento");

        Marca.setText("Marca ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_cadastrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_excluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_alterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_salvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_cancelar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tf_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_buscar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel6))
                                            .addGap(2, 2, 2)))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_custo, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                    .addComponent(tf_venda)
                                    .addComponent(tf_quantidade)
                                    .addComponent(tf_descricao)
                                    .addComponent(tf_codigo))
                                .addGap(90, 90, 90)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(Marca))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_marca, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                    .addComponent(tf_departamento))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Marca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_custo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_venda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cadastrar)
                    .addComponent(btn_excluir)
                    .addComponent(btn_alterar)
                    .addComponent(btn_salvar)
                    .addComponent(btn_cancelar))
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        String descricao = tf_descricao.getText();
        String codigo = tf_codigo.getText();
        String quantidade = tf_quantidade.getText();
        String valorCusto = tf_custo.getText();
        String valorVenda = tf_venda.getText();
        String departamento = tf_departamento.getText();
        String marca = tf_marca.getText();

        ProdutoModelo produto = new ProdutoModelo(descricao, codigo, quantidade, valorCusto, valorVenda, departamento, marca);
        try {
            produtoDao.cadastrarProduto(produto);
            JOptionPane.showMessageDialog(null, "Produto cadastrado com sucesso");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar o Produto", "Erro", JOptionPane.ERROR_MESSAGE);

        }
        limparCampos();
        atualizarTabelaProduto();
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        try {
            produtos = produtoDao.buscarProduto(tf_buscar.getText());
            DefaultTableModel model = (DefaultTableModel) tabela_produto.getModel();
            model.setNumRows(0);
            for (int i = 0; i < produtos.size(); i++) {
                ProdutoModelo produtoModelo = produtos.get(i);
                model.addRow(new Object[]{
                    produtoModelo.getCodigo(),
                    produtoModelo.getDescricao(),
                    produtoModelo.getQuantidade(),
                    produtoModelo.getValorCusto(),
                    produtoModelo.getValorVenda(),
                    produtoModelo.getDepartamento(),
                    produtoModelo.getMarca()
                });
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível localizar os produtos", "Erro", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        int linha = tabela_produto.getSelectedRow();
        if (linha < 0) {
            JOptionPane.showMessageDialog(null, "Selecione uma Produto", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        produtoSelecionado = produtos.get(linha);
        try {
            produtoDao.excluirProduto(produtoSelecionado.getCodigo());
            JOptionPane.showMessageDialog(null, "Produto excluído");
            atualizarTabelaProduto();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao excluir o Produto", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        String codigo = tf_codigo.getText();
        String descricao = tf_descricao.getText();
        String quantidade = tf_quantidade.getText();
        String valorCusto = tf_custo.getText();
        String valorVenda = tf_venda.getText();
        String departamento = tf_departamento.getText();
        String marca = tf_marca.getText();


        if (produtoSelecionado == null) {

            ProdutoModelo produtoModelo = new ProdutoModelo(descricao, codigo, quantidade, valorCusto, valorVenda, departamento, marca);

            try {
                produtoDao.cadastrarProduto(produtoModelo);
                JOptionPane.showMessageDialog(null, "Produto cadastrado");
                limparCampos();

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao salvar o Produto", "Erro", JOptionPane.ERROR_MESSAGE);

            }

        } else {
            produtoSelecionado.setCodigo(codigo);
            produtoSelecionado.setDescricao(descricao);
            produtoSelecionado.setQuantidade(quantidade);
            produtoSelecionado.setValorCusto(valorCusto);
            produtoSelecionado.setValorVenda(valorVenda);
            produtoSelecionado.setDepartamento(departamento);
            produtoSelecionado.setMarca(marca);

            try {
                System.out.println(produtoSelecionado);
                produtoDao.editar(produtoSelecionado);
                JOptionPane.showMessageDialog(null, "Prouto foi editado com sucesso");
                atualizarTabelaProduto();
                limparCampos();

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao editar o Produto", "Erro", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void btn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterarActionPerformed
        int row = tabela_produto.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Selecione um produto", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }

        produtoSelecionado = produtos.get(row);
        tf_codigo.setText(produtoSelecionado.getCodigo());
        tf_descricao.setText(produtoSelecionado.getDescricao());
        tf_quantidade.setText(produtoSelecionado.getQuantidade());
        tf_custo.setText(produtoSelecionado.getValorCusto());
        tf_venda.setText(produtoSelecionado.getValorVenda());
        tf_marca.setText(produtoSelecionado.getMarca());
        tf_departamento.setText(produtoSelecionado.getDepartamento());

    }//GEN-LAST:event_btn_alterarActionPerformed
    private void limparCampos() {
        tf_codigo.setText("");
        tf_descricao.setText("");
        tf_quantidade.setText("");
        tf_custo.setText("");
        tf_venda.setText("");
        tf_departamento.setText("");
        tf_marca.setText("");
    }

    public void atualizarTabelaProduto() {
        try {
            produtos = produtoDao.buscarProduto(tf_buscar.getText());

            DefaultTableModel model = (DefaultTableModel) tabela_produto.getModel();
            model.setNumRows(0);
            for (int i = 0; i < produtos.size(); i++) {
                ProdutoModelo produtoModelo = produtos.get(i);
                model.addRow(new Object[]{
                    produtoModelo.getCodigo(),
                    produtoModelo.getDescricao(),
                    produtoModelo.getQuantidade(),
                    produtoModelo.getValorCusto(),
                    produtoModelo.getValorVenda(),
                    produtoModelo.getDepartamento(),
                    produtoModelo.getMarca()});
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao atualizar os produtos", "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Marca;
    private javax.swing.JButton btn_alterar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabela_produto;
    private javax.swing.JTextField tf_buscar;
    private javax.swing.JTextField tf_codigo;
    private javax.swing.JTextField tf_custo;
    private javax.swing.JTextField tf_departamento;
    private javax.swing.JTextField tf_descricao;
    private javax.swing.JTextField tf_marca;
    private javax.swing.JTextField tf_quantidade;
    private javax.swing.JTextField tf_venda;
    // End of variables declaration//GEN-END:variables

    void setCloseIcon(Icon icon) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
